services:
  - type: web
    name: tt-tech-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: tt-tech-backend
          type: web
          property: url

  - type: web
    name: tt-tech-backend
    buildCommand: |
      npm install
      mkdir -p src/middleware
      cp -r backend/middleware/* src/middleware/
      cp -r backend/routes/* src/routes/
      cp -r backend/models/* src/models/
      cp -r backend/services/* src/services/
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
